source 'https://github.com/CocoaPods/Specs.git'

pod 'pop', '~> 1.0'
pod 'Doppelganger'
pod 'CWStatusBarNotification', '~> 2.2.2'
pod 'UberKit'
pod 'AFNetworking', '~> 2.0'
pod 'Bolts'
pod 'RJImageLoader'
pod 'LLSimpleCamera', '~> 2.1'
pod 'KRLCollectionViewGridLayout'